from ztpl_app_module_name.route import register_ztpl_app_module_name_route_handler
from ztpl_app_module_name.event import register_ztpl_app_module_name_event_handler
from ztpl_app_module_name.rpc import register_ztpl_app_module_name_rpc_handler