from module.ztpl_app_module_name.ztpl_app_crud_entity.repo.ztpl_app_crud_entity_repo import ZtplAppCrudEntityRepo
from module.ztpl_app_module_name.ztpl_app_crud_entity.repo.db_ztpl_app_crud_entity_repo import DBZtplAppCrudEntityRepo, DBZtplAppCrudEntityEntity
from module.ztpl_app_module_name.ztpl_app_crud_entity.ztpl_app_crud_entity_service import ZtplAppCrudEntityService
from module.ztpl_app_module_name.ztpl_app_crud_entity.ztpl_app_crud_entity_route import register_ztpl_app_crud_entity_api_route, register_ztpl_app_crud_entity_ui_route
from module.ztpl_app_module_name.ztpl_app_crud_entity.ztpl_app_crud_entity_rpc import register_ztpl_app_crud_entity_rpc
