configs:

  zrbStartDockerContainer:
    restartPolicy: on-failure
    _checkContainerState: |
      echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Waiting docker container '${CONTAINER_NAME}' running status${_NORMAL}"
      if [ "$(inspectDocker "container" ".State.Running" "${CONTAINER_NAME}")" != true ]
      then
        echo ${_RED}${CONTAINER_NAME} is not running${_NORMAL}
        exit 1
      fi
      echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Waiting docker container '${CONTAINER_NAME}' healthcheck${_NORMAL}"
      if [ "$(inspectDocker "container" ".State.Health" "${CONTAINER_NAME}")" = false ]
      then
        echo ${_RED}${CONTAINER_NAME} is not healthy${_NORMAL}
        exit 1
      fi
      echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Docker container '${CONTAINER_NAME}' is running${_NORMAL}"
    _checkCommand: |
      {{ if .GetConfig "checkCommand" -}}
      (echo $- | grep -Eq ^.*e.*$) && _OLD_STATE=-e || _OLD_STATE=+e
      set +e
      sleep 3
      {{ $checkCommand := .Util.Str.Trim (.GetConfig "checkCommand") "\n" -}}
      echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Run check in '${CONTAINER_NAME}': {{ .Util.Str.EscapeShellValue $checkCommand }}${_NORMAL}"
      docker exec "${CONTAINER_NAME}" {{ $checkCommand }}
      echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Sucessfully run check in '${CONTAINER_NAME}': {{ .Util.Str.EscapeShellValue $checkCommand }}${_NORMAL}"
      set "${_OLD_STATE}"
      {{ end -}}
    _checkConfigPorts: |
      {{ $this := . -}}
      {{ range $index, $port := .Util.Str.Split (.Util.Str.Trim (.GetConfig "ports") "\n ") "\n" -}}
        {{ if ne $port "" -}}
          {{ $portParts := $this.Util.Str.Split ($this.Util.Str.Trim $port  " ") ":" -}}
          {{ $hostPort := index $portParts 0 -}}
          echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Waiting for host port: '{{ $hostPort }}'${_NORMAL}"
          waitPort "localhost" {{ $hostPort }}
          echo "${_INSPECT_ICON} ${_BOLD}${_YELLOW}Host port '{{ $hostPort }}' is ready${_NORMAL}"
        {{ end -}}
      {{ end -}}
    _check: |
      {{ .GetConfig "_checkContainerState" }}
      {{ .GetConfig "_checkConfigPorts" }}
      {{ .GetConfig "_checkCommand" }}
      sleep 1
    check: ''
    