components:

  servicename-test:
    type: command
    labels:
      purpose: test
    env:
      SERVICENAME_HTTP_PORT: 4010
      GLOBAL_RMQ_CONNECTION_STRING: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${rmq}:5672/
      LOCAL_RMQ_CONNECTION_STRING: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${rmq}:5672/
      TEST_RMQ_CONNECTION_STRING: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${rmq}:5672/
    start: go test ./...
    dependencies:
      - rmq

  servicename:
    type: service
    labels:
      purpose: live
    origin: "" # fill this one with your git repository
    branch: master
    env:
      SERVICENAME_HTTP_PORT: 3010
      GLOBAL_RMQ_CONNECTION_STRING: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${rmq}:5672/
      LOCAL_RMQ_CONNECTION_STRING: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${rmq}:5672/
    start: go build -o app && ./app
    readinessCheck: curl ${servicename}:${SERVICENAME_HTTP_PORT}/readiness
    dependencies:
      - rmq

links:
  ../../libraries/go/transport:
    - ./transport
  ../../libraries/go/core:
    - ./core
