configs:

  makeSparkAppRunner:
    appIcon: 💥
    defaultAppDirectory: '{{ .ProjectName }}Spark'
    defaultAppPorts: |
      [
        "{{ .Template ".GetEnv \\\"SPARK_MASTER_UI_PORT\\\"" }}"
      ] 