env:
  GOPHER1_HTTP_PORT: 3011

components:

  gopher1-test:
    type: command
    labels:
      purpose: test integration-test end-to-end-test
      language: go
    start: go test ./..

  gopher1:
    type: service
    labels:
      purpose: service
      language: go
    origin: "" # fill this one with your git repository
    branch: master
    location: "."
    start: go build && ./app
    readinessUrl: http://${gopher1}:${GOPHER1_HTTP_PORT}/readiness
    dependencies:
      - rmq

links:
  ../../libraries/go/transport:
    - ./transport
