configs:

  addFastAppCrud:
    _skipCreationPath: ''
    _prepareVariables: |
      {{ .GetConfig "_prepareBaseStartCommand" }}
      {{ .GetConfig "_prepareBasePrepareCommand" }}
      {{ .GetConfig "_prepareBaseTestCommand" }}
      {{ .GetConfig "_prepareBaseCheckCommand" }}
      {{ .GetConfig "_prepareBaseReplacementMap" }}
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setAppCrudFirstField.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setRepoFieldDeclaration.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setRepoFieldInsert.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setRepoFieldUpdate.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setSchemaFieldDeclaration.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setTestField.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setVueComponent.sh"
    _integrate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/importInternalRouteHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerApiRouteHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerUiRouteHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerRpcHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerCrud.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerMenu.sh"
    _validate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/validate.sh"
    defaultAppDirectory: '{{ .ProjectName }}FastApp'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/template"
      ]

