configs:

  addFastAppCrud:
    _skipCreationPath: '${_ZRB_APP_DIRECTORY}/module/${_ZRB_SNAKE_APP_MODULE_NAME}/${_ZRB_SNAKE_APP_CRUD_ENTITY}'
    _prepareVariables: |
      {{ .GetConfig "_prepareBaseStartCommand" }}
      {{ .GetConfig "_prepareBasePrepareCommand" }}
      {{ .GetConfig "_prepareBaseTestCommand" }}
      {{ .GetConfig "_prepareBaseCheckCommand" }}
      {{ .GetConfig "_prepareBaseReplacementMap" }}
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setAppCrudFirstField.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setRepoFieldDeclaration.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setRepoFieldInsert.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setRepoFieldUpdate.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setSchemaFieldDeclaration.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setTestField.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/setVueComponent.sh"
    _integrate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/importCrudRouteHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerCrudApiRouteHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerCrudUiRouteHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerCrudRpcHandler.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerCrud.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/registerMigration.sh"
    _validate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/bash/validate.sh"
    defaultAppDirectory: '{{ .ProjectName }}FastApp'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrud/template"
      ]

