configs:

  zrbPulumi:
    pulumiStack: '{{ if .GetValue "pulumiStack" }}{{ .GetValue "pulumiStack" }}{{ else }}dev{{ end }}'
    pulumiUseLocalBackend: '{{ .GetValue "pulumiUseLocalBackend" }}'
    pulumiBackendUrl: ''
    _preparePulumi: |
      {{ if .Util.Bool.IsTrue (.GetConfig "pulumiUseLocalBackend") -}}
      if [ ! -z "${ZARUBA_CONFIG_PULUMI_BACKEND_URL}" ]
      then
        export PULUMI_BACKEND_URL=${ZARUBA_CONFIG_PULUMI_BACKEND_URL}
      else
        mkdir -p ./pulumiLock
        export PULUMI_BACKEND_URL="file://./pulumiLock"
      fi
      echo "${_YELLOW}Pulumi backend URL: ${PULUMI_BACKEND_URL}${_NORMAL}"
      {{ end -}}
      pulumi stack select "${ZARUBA_CONFIG_PULUMI_STACK}" || pulumi stack init "${ZARUBA_CONFIG_PULUMI_STACK}" 
      echo "${_YELLOW}Pulumi stack: ${ZARUBA_CONFIG_PULUMI_STACK}${_NORMAL}"
