env:
  GOPHER2_HTTP_PORT: 3012

components:

  gopher2-test:
    type: command
    labels:
      purpose: test
      language: go
    start: go test ./..

  gopher2:
    type: service
    labels:
      purpose: service
      language: go
    origin: "" # fill this one with your git repository
    branch: master
    location: "."
    start: go build && ./app
    readinessUrl: http://${gopher2}:${GOPHER1_HTTP_PORT}/readiness
    dependencies:
      - rmq

links:
  ../../libraries/go/transport:
    - ./transport
