tasks:

  makeMysqlHelmDeploymentTask:
    icon: 🚢
    extend: zrbMake
    dependencies:
      - zrbIsProject
      - makeMysqlHelmDeployment
    inputs:
      - deploymentDirectory
      - deploymentName
    configRef: makeMysqlHelmDeploymentTask

