configs:

  makeNodeJsAppRunner:
    appIcon: 🐸
    _prepareVariables: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/nodeJsAppRunner/bash/prepareVariables.sh"
    shouldNpmInstall: true
    shoulInstallTypeScript: false
    shouldCompileTypeScript: false
    shouldRemoveNodeModules: false
    shouldCleanNpmCache: false
    shouldRebuildNpm: false
    defaultNodeJsAppPorts: |
      [
        "3000"
      ]
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/native/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/nodeJsAppRunner/appRunnerTemplate"
      ]
  
