_setReplacementMap "ztplAppBuildImageCommand" "${_ZRB_APP_BUILD_IMAGE_COMMAND}"
_setReplacementMap "ztplAppCheckCommand" "${_ZRB_APP_CHECK_COMMAND}"
_setReplacementMap "ztplAppContainerName" "${_ZRB_APP_CONTAINER_NAME}"
_setReplacementMap "ztplAppContainerVolumes" "${_ZRB_APP_CONTAINER_VOLUMES}"
_setReplacementMap "ztplAppDependencies" "${_ZRB_APP_DEPENDENCIES}"
_setReplacementMap "ztplAppDirectory" "${_ZRB_APP_DIRECTORY}"
_setReplacementMap "ztplTaskAppLocation" "${_ZRB_TASK_APP_LOCATION}"
_setReplacementMap "ztplAppEnvPrefix" "${_ZRB_APP_ENV_PREFIX}"
_setReplacementMap "ztplAppEnvs" "${_ZRB_APP_ENVS}"
_setReplacementMap "ztplAppHelmChartUrl" "${_ZRB_APP_HELM_CHART_URL}"
_setReplacementMap "ztplAppImageName" "${_ZRB_APP_IMAGE_NAME}"
_setReplacementMap "ztplAppName" "${_ZRB_APP_NAME}"
_setReplacementMap "ZtplAppName" "${_ZRB_APP_PASCAL_NAME}"
_setReplacementMap "ztplAppPrepareCommand" "${_ZRB_APP_PREPARE_COMMAND}"
_setReplacementMap "ztplAppPorts" "${_ZRB_APP_PORTS}"
_setReplacementMap "ztplAppPushImageCommand" "${_ZRB_APP_PUSH_IMAGE_COMMAND}"
_setReplacementMap "ztplAppRunnerVersion" "${_ZRB_APP_RUNNER_VERSION}"
_setReplacementMap "ztplAppStartCommand" "${_ZRB_APP_START_COMMAND}"
_setReplacementMap "ztplAppStartContainerCommand" "${_ZRB_APP_START_CONTAINER_COMMAND}"
_setReplacementMap "ztplAppTestCommand" "${_ZRB_APP_TEST_COMMAND}"
_setReplacementMap "ztplAppCrudEntity" "${_ZRB_APP_CRUD_ENTITY}"
_setReplacementMap "ztplAppCrudFields" "${_ZRB_APP_CRUD_FIELDS}"
_setReplacementMap "ztplAppEventName" "${_ZRB_APP_EVENT_NAME}"
_setReplacementMap "ztplAppHttpMethod" "${_ZRB_APP_HTTP_METHOD}"
_setReplacementMap "ztplAppModuleName" "${_ZRB_APP_MODULE_NAME}"
_setReplacementMap "ztplAppRpcName" "${_ZRB_APP_RPC_NAME}"
_setReplacementMap "ztplAppUrl" "${_ZRB_APP_URL}"
_setReplacementMap "[\t ]*ztplAppYamlPorts" "${_ZRB_APP_YAML_PORTS}"
_setReplacementMap "[\t ]*ztplAppYamlEnvs" "${_ZRB_APP_YAML_ENVS}"
_setReplacementMap "[\t ]*ztplAppYamlContainerVolumes" "${_ZRB_APP_YAML_CONTAINER_VOLUMES}"

"${ZARUBA_HOME}/zaruba" yaml print "${_ZRB_REPLACEMENT_MAP}"