configs:

  zrbMakeAppRunner:
    _skipCreationPath: './zaruba-tasks/${_ZRB_APP_NAME}'
    _taskIndexPath: './zaruba-tasks/${_ZRB_APP_NAME}/index.yaml'
    _nativePrepareAppRunnerTaskName: 'start${_ZRB_PASCAL_APP_NAME}'
    _containerPrepareAppRunnerTaskName: 'start${_ZRB_PASCAL_APP_NAME}Container'
    _registerAppDeploymentTasks: ''
    _setProjectValue: |
      echo "Set project value run${_ZRB_PASCAL_APP_NAME}InLocal to true"
      ${ZARUBA_BIN} project setValue "run${_ZRB_PASCAL_APP_NAME}InLocal" true
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template"
      ]