configs:

  makeKafkaAppRunner:
    appIcon: 🪠
    defaultAppDirectory: '{{ .ProjectName }}Kafka'
    defaultAppPorts: |
      [
        "{{ .Template ".GetEnv \\\"ZOOKEEPER_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"KAFKA_JMX_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"KAFKA_LISTENER_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"SCHEMA_REGISTRY_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"CONNECT_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"CONTROL_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"KSQL_DB_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"REST_PROXY\\\"" }}"
      ]