configs:
 
  addFastAppModule:
    _skipCreationPath: '${_ZRB_APP_DIRECTORY}/module/${_ZRB_SNAKE_APP_MODULE_NAME}'
    _integrate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerModule.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerEnv.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerAlembicConfig.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerCreateMigrationCommand.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerMigrateCommand.sh"
    defaultAppDirectory: '{{ .ProjectName }}FastApp'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/template"
      ]