configs:
 
  addFastAppModule:
    _skipCreationPath: '${_ZRB_APP_DIRECTORY}/modules/${_ZRB_APP_MODULE_NAME}'
    _integrate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerModule.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerUi.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/bash/registerEnv.sh"
    defaultAppDirectory: '{{ .ProjectName }}FastApp'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppModule/template"
      ]