components:

  servicename-test:
    type: command
    labels:
      purpose: test
    env:
      SERVICENAME_HTTP_PORT: 4010
      GLOBAL_RMQ_CONNECTION_STRING: ${GLOBAL_RMQ_CONNECTION_STRING}
      LOCAL_RMQ_CONNECTION_STRING: ${LOCAL_RMQ_CONNECTION_STRING}
      TEST_RMQ_CONNECTION_STRING: ${TEST_RMQ_CONNECTION_STRING}
    start: npm test
    dependencies:
      - rmq

  servicename:
    type: service
    labels:
      purpose: live
    origin: "" # fill this one with your git repository
    branch: master
    env:
      SERVICENAME_HTTP_PORT: 3010
      GLOBAL_RMQ_CONNECTION_STRING: ${GLOBAL_RMQ_CONNECTION_STRING}
      LOCAL_RMQ_CONNECTION_STRING: ${LOCAL_RMQ_CONNECTION_STRING}
    start: npm start
    readinessUrl: http://${servicename}:${SERVICENAME_HTTP_PORT}/readiness
    dependencies:
      - rmq

links:
  ../../libraries/typescript/transport:
    - ./src/transport
  ../../libraries/typescript/core:
    - ./src/core
