tasks:

  makeSimpleDockerComposeAppRunner:
    icon: 🐳
    extend: makeDockerComposeAppRunner
    dependencies:
      - makeSimpleDockerComposeApp
    inputs:
      - appDirectory
      - appName
      - appEnvs
      - appPorts
    configRef: makeSimpleDockerComposeAppRunner