configs:

  makeNativeAppRunner:
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/native/template"
      ]