tasks:

  makeDockerComposeAppRunner:
    icon: 🐳
    extend: zrbMakeAppRunner
    inputs:
      - appDirectory
      - appName
      - appEnvs
      - appContainerName
    configRef: makeDockerComposeAppRunner