configs:
 
  makeMaterializeApp:
    defaultAppDirectory: '{{ .ProjectName }}Materialize'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/materialize/appTemplate"
      ]