# sparkMaster envs
_ZRB_APP_SPARK_MASTER_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/sparkMaster")"
# yaml
_ZRB_APP_YAML_SPARK_MASTER_ENVS="$(_getYamlEnvs "${_ZRB_APP_SPARK_MASTER_ENVS}" "${_ZRB_APP_ENV_PREFIX}")"

# sparkWorker envs
_ZRB_APP_SPARK_WORKER_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/sparkWorker")"
# yaml
_ZRB_APP_YAML_SPARK_WORKER_ENVS="$(_getYamlEnvs "${_ZRB_APP_SPARK_WORKER_ENVS}" "${_ZRB_APP_ENV_PREFIX}_SPARK_WORKER")"

# ports
_ZRB_APP_SPARK_MASTER_YAML_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_SPARK_MASTER_PORTS}")"
_ZRB_APP_SPARK_WORKER_YAML_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_SPARK_WORKER_PORTS}")"

