configs:

  makeAirbyteAppRunner:
    appIcon: 🪂
    defaultAppDirectory: '{{ .ProjectName }}Airbyte'
    defaultAppPorts: |
      [
        "{{ .Template ".GetEnv \\\"SERVER_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"WEB_PORT\\\"" }}",
        "{{ .Template ".GetEnv \\\"TEMPORAL_PORT\\\"" }}"
      ]
   