# https://github.com/bitnami/bitnami-docker-airflow/blob/master/docker-compose.yml
version: '2'

services:

  postgresql:
    build: ./postgresql
    image: ${DOCKER_COMPOSE_IMAGE_NAME:-airflow}-postgresql:${DOCKER_COMPOSE_IMAGE_TAG:-latest}
    hostname: postgresql
    container_name: ztplAppContainerNamePostgresql
    restart: unless-stopped
    volumes:
      - '${DOCKER_COMPOSE_VOLUME:-./volumes}/postgresql:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  redis:
    build: ./redis
    image: ${DOCKER_COMPOSE_IMAGE_NAME:-airflow}-redis:${DOCKER_COMPOSE_IMAGE_TAG:-latest}
    hostname: redis
    container_name: ztplAppContainerNameRedis
    restart: unless-stopped
    volumes:
      - '${DOCKER_COMPOSE_VOLUME:-./volumes}/redis:/bitnami'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-scheduler:
    build: ./airflow-scheduler
    image: ${DOCKER_COMPOSE_IMAGE_NAME:-airflow}-scheduler:${DOCKER_COMPOSE_IMAGE_TAG:-latest}
    hostname: airflow-scheduler
    container_name: ztplAppContainerNameScheduler
    restart: unless-stopped
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow

  airflow-worker:
    build: ./airflow-worker
    image: ${DOCKER_COMPOSE_IMAGE_NAME:-airflow}-worker:${DOCKER_COMPOSE_IMAGE_TAG:-latest}
    hostname: airflow-worker
    container_name: ztplAppContainerNameWorker
    restart: unless-stopped
    volumes:
      - '${DOCKER_COMPOSE_VOLUME:-./volumes}/airflow/dags:/opt/bitnami/airflow/dags'
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow

  airflow:
    build: ./airflow
    image: ${DOCKER_COMPOSE_IMAGE_NAME:-airflow}:${DOCKER_COMPOSE_IMAGE_TAG:-latest}
    hostname: airflow
    container_name: ztplAppContainerName
    restart: unless-stopped
    volumes:
      - '${DOCKER_COMPOSE_VOLUME:-./volumes}/airflow/dags:/opt/bitnami/airflow/dags'
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD:-Alch3mist}
      - AIRFLOW_USERNAME=${AIRFLOW_USER:-root}
      - AIRFLOW_EMAIL=${AIRFLOW_EMAIL:-root@stalchmst.com}
    ports:
      - '${AIRFLOW_WEB_SERVER_PORT:-8080}:8080'