# kafka envs
_ZRB_APP_KAFKA_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/kafka")"
# hosts values
_ZRB_APP_KAFKA_ENVS="$("${ZARUBA_BIN}" map set "${_ZRB_APP_KAFKA_ENVS}" "KAFKA_CFG_ZOOKEEPER_CONNECT" "${_ZRB_APP_CONTAINER_NAME}Zookeeper:2181")"
# yaml
_ZRB_APP_YAML_KAFKA_ENVS="$(_getYamlEnvs "${_ZRB_APP_KAFKA_ENVS}" "${_ZRB_APP_ENV_PREFIX}")"

# kafka connect envs
_ZRB_APP_KAFKA_CONNECT_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/kafkaConnect")"
# hosts values
_ZRB_APP_KAFKA_CONNECT_ENVS="$("${ZARUBA_BIN}" map set "${_ZRB_APP_KAFKA_CONNECT_ENVS}" "CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL" "http://${_ZRB_APP_CONTAINER_NAME}KafkaSchemaRegistry:8035")"
_ZRB_APP_KAFKA_CONNECT_ENVS="$("${ZARUBA_BIN}" map set "${_ZRB_APP_KAFKA_CONNECT_ENVS}" "CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL" "http://${_ZRB_APP_CONTAINER_NAME}KafkaSchemaRegistry:8035")"
# yaml
_ZRB_APP_YAML_KAFKA_CONNECT_ENVS="$(_getYamlEnvs "${_ZRB_APP_KAFKA_CONNECT_ENVS}" "${_ZRB_APP_ENV_PREFIX}_CONNECT")"

# kafka schema registry envs
_ZRB_APP_KAFKA_SCHEMA_REGISTRY_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/schemaRegistry")"
# hosts values
_ZRB_APP_KAFKA_SCHEMA_REGISTRY_ENVS="$("${ZARUBA_BIN}" map set "${_ZRB_APP_KAFKA_SCHEMA_REGISTRY_ENVS}" "SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS" "PLAINTEXT://${_ZRB_APP_CONTAINER_NAME}Kafka:8082")"
# yaml
_ZRB_APP_YAML_KAFKA_SCHEMA_REGISTRY_ENVS="$(_getYamlEnvs "${_ZRB_APP_KAFKA_CONNECT_ENVS}" "${_ZRB_APP_ENV_PREFIX}_SCHEMA_REGISTRY")"

# akhq envs
_ZRB_APP_AKHQ_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/akhq")"
# hosts values
_AKHQ_CONFIG="$("${ZARUBA_BIN}" map get "${_ZRB_APP_AKHQ_ENVS}" "AKHQ_CONFIGURATION")"
_AKHQ_CONFIG="$("${ZARUBA_BIN}" str replace "${_AKHQ_CONFIG}" "{\"kafka:9092\": \"${_ZRB_APP_CONTAINER_NAME}Kafka:9092\", \"schema-registry:8085\": \"${_ZRB_APP_CONTAINER_NAME}KafkaSchemaRegistry:8085\", \"connect:8083\": \"${_ZRB_APP_CONTAINER_NAME}KafkaConnect:8083\"}")"
_ZRB_APP_AKHQ_ENVS="$("${ZARUBA_BIN}" map set "${_ZRB_APP_AKHQ_ENVS}" "AKHQ_CONFIGURATION" "${_AKHQ_CONFIG}")"
# yaml
_ZRB_APP_YAML_AKHQ_ENVS="$(_getYamlEnvs "${_ZRB_APP_AKHQ_ENVS}" "${_ZRB_APP_ENV_PREFIX}_AKHQ")"

# zookeeper envs
_ZRB_APP_ZOOKEEPER_ENVS="$("${ZARUBA_BIN}" path getEnv "${_ZRB_APP_DIRECTORY}/zookeeper")"
# yaml
_ZRB_APP_YAML_ZOOKEEPER_ENVS="$(_getYamlEnvs "${_ZRB_APP_ZOOKEEPER_ENVS}" "${_ZRB_APP_ENV_PREFIX}_ZOOKEEPER")"

# ports
_ZRB_APP_YAML_AKHQ_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_AKHQ_PORTS}")"
_ZRB_APP_YAML_KAFKA_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_KAFKA_PORTS}")"
_ZRB_APP_YAML_KAFKA_CONNECT_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_KAFKA_CONNECT_PORTS}")"
_ZRB_APP_YAML_KAFKA_SCHEMA_REGISTRY_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_KAFKA_SCHEMA_REGISTRY_PORTS}")"
_ZRB_APP_YAML_ZOOKEEPER_PORTS="$("${ZARUBA_BIN}" list join "${_ZRB_APP_ZOOKEEPER_PORTS}")"