_setReplacementMap "[\t ]*ztplAppYamlAkhqEnvs" "${_ZRB_APP_YAML_AKHQ_ENVS}"
_setReplacementMap "[\t ]*ztplAppYamlZookeeperEnvs" "${_ZRB_APP_YAML_ZOOKEEPER_ENVS}"
_setReplacementMap "[\t ]*ztplAppYamlKafkaEnvs" "${_ZRB_APP_YAML_KAFKA_ENVS}"
_setReplacementMap "[\t ]*ztplAppYamlKafkaConnectEnvs" "${_ZRB_APP_YAML_KAFKA_CONNECT_ENVS}"
_setReplacementMap "[\t ]*ztplAppYamlKafkaSchemaRegistryEnvs" "${_ZRB_APP_YAML_KAFKA_SCHEMA_REGISTRY_ENVS}"

_setReplacementMap "[\t ]*ztplAppYamlAkhqPorts" "${_ZRB_APP_YAML_AKHQ_PORTS}"
_setReplacementMap "[\t ]*ztplAppYamlZookeeperPorts" "${_ZRB_APP_YAML_ZOOKEEPER_PORTS}"
_setReplacementMap "[\t ]*ztplAppYamlKafkaPorts" "${_ZRB_APP_YAML_KAFKA_PORTS}"
_setReplacementMap "[\t ]*ztplAppYamlKafkaConnectPorts" "${_ZRB_APP_YAML_KAFKA_CONNECT_PORTS}"
_setReplacementMap "[\t ]*ztplAppYamlKafkaSchemaRegistryPorts" "${_ZRB_APP_YAML_KAFKA_SCHEMA_REGISTRY_PORTS}"