from project.serviceGen import ServiceGen
from project.serviceTaskGen import ServiceTaskGen
from project.dockerTaskGen import DockerTaskGen
from project.helpers import get_service_task_template, get_docker_task_template, get_service_template,get_container_name_by_image, get_task_name_by_location, get_main_file_name