configs:

  showSolidPrinciple:
    start: |
      echo "${_BOLD}${_YELLOW} S ${_NORMAL}${_YELLOW} Single Responsibility Principle ${_NORMAL}"
      echo "${_BOLD}${_YELLOW} O ${_NORMAL}${_YELLOW} Open/Closed Principle ${_NORMAL}"
      echo "${_BOLD}${_YELLOW} L ${_NORMAL}${_YELLOW} Liskov's Substitution Principle ${_NORMAL}"
      echo "${_BOLD}${_YELLOW} I ${_NORMAL}${_YELLOW} Interface Segregation Principle ${_NORMAL}"
      echo "${_BOLD}${_YELLOW} D ${_NORMAL}${_YELLOW} Dependency Inversion Principle ${_NORMAL}"

