configs:

  makePostgresqlAppRunner:
    appIcon: 🐘
    appCheckCommand: pg_isready -U "{{ .Template ".GetEnv \"POSTGRESQL_USERNAME\"" }}"
    defaultAppDirectory: '{{ .ProjectName }}Postgresql'
    defaultAppPorts: |
      [
        "5432"
      ]
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/dockerContainer/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/postgresql/appRunnerTemplate"
      ]  