configs:
 
  makeSimpleTypeScriptApp:
    defaultAppDirectory: '{{ .ProjectName }}App'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/simpleTypeScriptApp/appTemplate"
      ]