configs:
 
  addFastAppPage:
    _skipCreationPath: ''
    _prepareVariables: ''
    _integrate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppPage/bash/addRouteHandler.sh"
    defaultAppDirectory: '{{ .ProjectName }}FastApp'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppPage/template"
      ]
