from modules.ztplAppModuleName.ztplAppCrudEntity.repos.ztplAppCrudEntityRepo import ZtplAppCrudEntityRepo
from modules.ztplAppModuleName.ztplAppCrudEntity.repos.dbZtplAppCrudEntityRepo import DBZtplAppCrudEntityRepo, DBZtplAppCrudEntityEntity
from modules.ztplAppModuleName.ztplAppCrudEntity.ztplAppCrudEntityService import ZtplAppCrudEntityService
from modules.ztplAppModuleName.ztplAppCrudEntity.ztplAppCrudEntityRoute import register_ztpl_app_crud_entity_api_route, register_ztpl_app_crud_entity_ui_route
from modules.ztplAppModuleName.ztplAppCrudEntity.ztplAppCrudEntityRpc import register_ztpl_app_crud_entity_rpc
