configs:

  makeElasticsearchAppRunner:
    appIcon: 🍜
    defaultAppDirectory: '{{ .ProjectName }}Elasticsearch'
    defaultAppPorts: |
      [
        "{{ .Template ".GetEnv \\\"ELASTICSEARCH_PORT_NUMBER\\\"" }}",
        "{{ .Template ".GetEnv \\\"ELASTICSEARCH_NODE_PORT_NUMBER\\\"" }}"
      ]