configs:
 
  makeElasticsearchApp:
    defaultAppDirectory: '{{ .ProjectName }}Elasticsearch'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/elasticsearch/appTemplate"
      ]