configs:
 
  addFastAppCrudField:
    _skipCreationPath: ''
    _integrate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrudField/bash/addSchemaFieldDeclaration.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrudField/bash/addDbRepoField.sh"
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrudField/bash/addVueComponent.sh"
    _validate: |
      . "{{ .ZarubaHome }}/zaruba-tasks/make/fastAppCrudField/bash/validate.sh"
    defaultAppDirectory: '{{ .ProjectName }}FastApp'
    templateLocations: '[]'
