configs:

  makeJupyterNotebookAppRunner:
    appIcon: 🧪
    defaultAppDirectory: '{{ .ProjectName }}JupyterNotebook'
    defaultAppPorts: |
      [
        "8888"
      ]
    defaultAppContainerVolumes: '[]'