configs:
 
  makeJupyterNotebookApp:
    defaultAppDirectory: '{{ .ProjectName }}JupyterNotebook'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/jupyterNotebook/appTemplate"
      ]