# scheduler envs
_ZRB_APP_SCHEDULER_ENVS="$("${ZARUBA_HOME}/zaruba" path getEnv "${_ZRB_APP_DIRECTORY}/airflowScheduler")"
_ZRB_APP_SCHEDULER_ENVS="$("${ZARUBA_HOME}/zaruba" map merge "${_ZRB_APP_SCHEDULER_ENVS}" "${_ZRB_APP_ENVS}")"
# hosts values
_ZRB_APP_SCHEDULER_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_SCHEDULER_ENVS}" "AIRFLOW_WEBSERVER_HOST" "${_ZRB_APP_CONTAINER_NAME}Web")"
_ZRB_APP_SCHEDULER_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_SCHEDULER_ENVS}" "AIRFLOW_DATABASE_HOST" "${_ZRB_APP_CONTAINER_NAME}Postgresql")"
_ZRB_APP_SCHEDULER_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_SCHEDULER_ENVS}" "REDIS_HOST" "${_ZRB_APP_CONTAINER_NAME}Redis")"
# yaml
_ZRB_APP_YAML_SCHEDULER_ENVS="$(_getYamlEnvs "${_ZRB_APP_SCHEDULER_ENVS}" "${_ZRB_APP_ENV_PREFIX}")"

# web envs
_ZRB_APP_WEB_ENVS="$("${ZARUBA_HOME}/zaruba" path getEnv "${_ZRB_APP_DIRECTORY}/airflowWeb")"
_ZRB_APP_WEB_ENVS="$("${ZARUBA_HOME}/zaruba" map merge "${_ZRB_APP_WEB_ENVS}" "${_ZRB_APP_ENVS}")"
# hosts values
_ZRB_APP_WEB_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_WEB_ENVS}" "AIRFLOW_DATABASE_HOST" "${_ZRB_APP_CONTAINER_NAME}Postgresql")"
_ZRB_APP_WEB_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_WEB_ENVS}" "REDIS_HOST" "${_ZRB_APP_CONTAINER_NAME}Redis")"
# yaml
_ZRB_APP_YAML_WEB_ENVS="$(_getYamlEnvs "${_ZRB_APP_WEB_ENVS}" "${_ZRB_APP_ENV_PREFIX}")"

# worker envs
_ZRB_APP_WORKER_ENVS="$("${ZARUBA_HOME}/zaruba" path getEnv "${_ZRB_APP_DIRECTORY}/airflowWorker")"
_ZRB_APP_WORKER_ENVS="$("${ZARUBA_HOME}/zaruba" map merge "${_ZRB_APP_WORKER_ENVS}" "${_ZRB_APP_ENVS}")"
# hosts values
_ZRB_APP_WORKER_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_WORKER_ENVS}" "AIRFLOW_WEBSERVER_HOST" "${_ZRB_APP_CONTAINER_NAME}Web")"
_ZRB_APP_WORKER_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_WORKER_ENVS}" "AIRFLOW_DATABASE_HOST" "${_ZRB_APP_CONTAINER_NAME}Postgresql")"
_ZRB_APP_WORKER_ENVS="$("${ZARUBA_HOME}/zaruba" map set "${_ZRB_APP_WORKER_ENVS}" "REDIS_HOST" "${_ZRB_APP_CONTAINER_NAME}Redis")"
# yaml
_ZRB_APP_YAML_WORKER_ENVS="$(_getYamlEnvs "${_ZRB_APP_WORKER_ENVS}" "${_ZRB_APP_ENV_PREFIX}")"

# postgresql envs
_ZRB_APP_POSTGRESQL_ENVS="$("${ZARUBA_HOME}/zaruba" path getEnv "${_ZRB_APP_DIRECTORY}/postgresql")"
_ZRB_APP_YAML_POSTGRESQL_ENVS="$(_getYamlEnvs "${_ZRB_APP_POSTGRESQL_ENVS}" "${_ZRB_APP_ENV_PREFIX}_POSTGRESQL")"

# redis envs
_ZRB_APP_REDIS_ENVS="$("${ZARUBA_HOME}/zaruba" path getEnv "${_ZRB_APP_DIRECTORY}/redis")"
_ZRB_APP_YAML_REDIS_ENVS="$(_getYamlEnvs "${_ZRB_APP_REDIS_ENVS}" "${_ZRB_APP_ENV_PREFIX}_REDIS")"

_ZRB_APP_POSTGRESQL_YAML_PORTS="$("${ZARUBA_HOME}/zaruba" list join "${_ZRB_APP_POSTGRESQL_PORTS}")"
_ZRB_APP_REDIS_YAML_PORTS="$("${ZARUBA_HOME}/zaruba" list join "${_ZRB_APP_REDIS_PORTS}")"
_ZRB_APP_WEB_YAML_PORTS="$("${ZARUBA_HOME}/zaruba" list join "${_ZRB_APP_WEB_PORTS}")"