configs:

  zrbGenerateAndRun:
    shouldInitConfigVariables: true
    shouldInitConfigMapVariable: true
    shouldInitEnvMapVariable: true
    templateLocation: '{{ .ZarubaHome }}/zaruba-tasks/_base/generateAndRun/template'
    script: '{{ .GetValue "script" }}'
    sql: '{{ .GetValue "sql" }}'
    generatedScriptLocation: '{{ .GetProjectPath "tmp" }}/{{ .Name }}.script.{{ .UUID }}'
    runGeneratedScript: '{{ .GetProjectPath "tmp" }}/{{ .Name }}/run.sh'
    _prepareBaseVariables: '. "{{ .ZarubaHome }}/zaruba-tasks/_base/generateAndRun/bash/prepareVariables.sh"'
    _prepareBaseReplacementMap: '. "{{ .ZarubaHome }}/zaruba-tasks/_base/generateAndRun/bash/prepareReplacementMap.sh"'
    _prepareVariables: ''
    _prepareReplacementMap: ''
    _validateTemplateLocation: '. "{{ .ZarubaHome }}/zaruba-tasks/_base/generateAndRun/bash/validateTemplateLocation.sh"'
    _validate: ''
    _start: |
      . "{{ .ZarubaHome }}/zaruba-tasks/_base/generateAndRun/bash/util.sh"
      _ZRB_TEMPLATE_LOCATION='{{ .GetConfig "templateLocation" }}'
      _ZRB_GENERATED_SCRIPT_LOCATION='{{ .GetConfig "generatedScriptLocation" }}'
      _ZRB_REPLACEMENT_MAP='{}'
      __ZRB_PWD=$(pwd)
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Prepare${_NORMAL}"
      {{ .GetConfig "_prepareBaseVariables" }}
      {{ .GetConfig "_prepareVariables" }}
      {{ .GetConfig "_prepareBaseReplacementMap" }}
      {{ .GetConfig "_prepareReplacementMap" }}
      cd "${__ZRB_PWD}"
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Validate${_NORMAL}"
      {{ .GetConfig "_validateTemplateLocation" }}
      {{ .GetConfig "_validate" }}
      cd "${__ZRB_PWD}"
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Generate${_NORMAL}"
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Template Location:${_NORMAL} ${_ZRB_TEMPLATE_LOCATION}"
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Generated Script Location:${_NORMAL} ${_ZRB_GENERATED_SCRIPT_LOCATION}"
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Replacement Map:${_NORMAL} ${_ZRB_REPLACEMENT_MAP}"
      mkdir -p "${_ZRB_GENERATED_SCRIPT_LOCATION}"
      "{{ .ZarubaBin }}" generate "${_ZRB_TEMPLATE_LOCATION}" "${_ZRB_GENERATED_SCRIPT_LOCATION}" "${_ZRB_REPLACEMENT_MAP}"
      cd "${__ZRB_PWD}"
      echo "${_YELLOW}${_START_ICON} Generated Script${_NORMAL}"
      echo "${ZARUBA_CONFIG_RUN_GENERATED_SCRIPT}"
      echo "${_YELLOW}${_START_ICON} Run Generated Script${_NORMAL}"
      {{ .GetConfig "runGeneratedScript" }}
      cd "${__ZRB_PWD}"
    start: ''
    afterStart: |
      echo ${_SUCCESS_ICON}${_SUCCESS_ICON}${_SUCCESS_ICON}
      echo "${_BOLD}${_YELLOW}Done${_NORMAL}"
