tasks:

  parentTaskName:
    configs:
      parentKey: '{{ .GetConfig "key" }}'
  

  taskName:
    extend: parentTaskName
    configRef: configRefName
    configs:
      key: value


configs:

  configRefName:
    refKey: refValue