configs:
 
  makeContainerRegistryApp:
    defaultAppDirectory: '{{ .ProjectName }}ContainerRegistry'
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/containerRegistry/appTemplate"
      ]