from repos.zarubaEntityName import ZarubaEntityNameRepo
from zarubaModuleName.handleZarubaEntityNameHttp import handle_http as handle_zaruba_entity_name_http
from zarubaModuleName.handleZarubaEntityNameRpc import handle as handle_zaruba_entity_name_rpc