"""20221106201120 cms

Revision ID: 3dc444e54106
Revises: e768af779211
Create Date: 2022-11-06 20:11:21.398067

"""
from alembic import op
import sqlalchemy as sa
import os


# revision identifiers, used by Alembic.
revision = '3dc444e54106'
down_revision = '2c643d4333f3'
branch_labels = None
depends_on = None


def run_migration() -> bool:
    return os.getenv('MIGRATION_RUN_ALL', '0') != '0' or os.getenv('APP_ENABLE_CMS_MODULE', '1') != '0'


def upgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_types',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('template', sa.String(length=255), nullable=True),
        sa.Column('json_attributes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_types_json_attributes'), 'content_types', ['json_attributes'], unique=False)
    op.create_index(op.f('ix_content_types_id'), 'content_types', ['id'], unique=False)
    op.create_index(op.f('ix_content_types_name'), 'content_types', ['name'], unique=False)
    op.create_index(op.f('ix_content_types_template'), 'content_types', ['template'], unique=False)
    op.create_table('contents',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('content_type_id', sa.String(length=36), sa.ForeignKey('content_types.id'), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_description'), 'contents', ['description'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_content_type_id'), 'contents', ['content_type_id'], unique=False)
    op.create_table('content_attributes',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('content_id', sa.String(length=36), sa.ForeignKey('contents.id'), nullable=False),
        sa.Column('key', sa.String(length=255), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(length=36), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_content_attributes_content_id'), 'content_attributes', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_attributes_id'), 'content_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_content_attributes_key'), 'content_attributes', ['key'], unique=False)
    op.create_index(op.f('ix_content_attributes_value'), 'content_attributes', ['value'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    if not run_migration():
        return None
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_attributes_value'), table_name='content_attributes')
    op.drop_index(op.f('ix_content_attributes_key'), table_name='content_attributes')
    op.drop_index(op.f('ix_content_attributes_id'), table_name='content_attributes')
    op.drop_index(op.f('ix_content_attributes_content_id'), table_name='content_attributes')
    op.drop_table('content_attributes')
    op.drop_index(op.f('ix_content_types_template'), table_name='content_types')
    op.drop_index(op.f('ix_content_types_name'), table_name='content_types')
    op.drop_index(op.f('ix_content_types_id'), table_name='content_types')
    op.drop_index(op.f('ix_content_types_json_attributes'), table_name='content_types')
    op.drop_table('content_types')
    op.drop_index(op.f('ix_contents_content_type_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_description'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
