configs:

  prepareZtplDeploymentName:
    awsRegion: '{{ if .GetValue "ztplDeploymentNameRegion" }}{{ .GetValue "ztplDeploymentNameRegion" }}{{ else }}us-east-2{{ end }}'
    start: |
      {{ .GetConfig "_preparePulumi" }}
      pulumi config set aws:region "${ZARUBA_CONFIG_AWS_REGION}"
      if [ ! -d "./venv" ]
      then
        python -m venv ./venv
        ./venv/bin/python -m pip install --upgrade pip
      fi
      source ./venv/bin/activate
      pip install -r requirements.txt