tasks:

  zrbBuildDockerCompose:
    icon: 🐳
    private: true
    timeout: 1h
    description: |
      Build docker compose.
    extend: zrbRunShellScript
    dependencies:
      - updateProjectLinks
    configRefs:
      - zrbDocker
      - zrbPrepareDockerComposeEnv
      - zrbBuildDockerCompose