tasks:

  zrbPushDockerCompose:
    icon: 🐳
    private: true
    description: |
      Push docker compose.
    extend: zrbRunShellScript
    dependencies:
      - updateProjectLinks
    configRefs: 
      - zrbDocker
      - zrbPrepareDockerComposeEnv
      - zrbPushDockerCompose