tasks:

  zrbPullDockerCompose:
    icon: 🐳
    private: true
    timeout: 1h
    description: |
      Pull docker compose.
    extend: zrbRunShellScript
    dependencies:
      - updateProjectLinks
    configRefs: 
      - zrbDocker
      - zrbPrepareDockerComposeEnv
      - zrbPullDockerCompose