tasks:

  zrbRemoveDockerCompose:
    icon: 🐳
    private: true
    description: |
      Remove docker compose.
    extend: zrbRunShellScript
    dependencies:
      - updateProjectLinks
    configRefs: 
      - zrbDocker
      - zrbRemoveDockerCompose