configs:

  prepareZtplDeploymentName:
    start: |
      # Activate venv
      #
      if [ ! -d "./venv" ]
      then
        echo "${_YELLOW}${_CONSTRUCTION_ICON} Create virtual environment.${_NORMAL}"
        python -m venv ./venv
        ./venv/bin/python -m pip install --upgrade pip
      fi
      source ./venv/bin/activate
      echo "${_YELLOW}${_CONSTRUCTION_ICON} Install pip packages.${_NORMAL}"
      pip install -r requirements.txt
      #
      # Prepare Chart
      #
      . '{{ .GetProjectPath "zaruba-tasks/ztplDeploymentName/bash/prepareChart.sh" }}'