configs:

  makeEksDeploymentTask:
    appIcon: 📙
    defaultDeploymentDirectory: '{{ .ProjectName }}Eks'
    _skipCreationPath: 'zaruba-tasks/${_ZRB_DEPLOYMENT_NAME}'
    _taskIndexPath: './zaruba-tasks/${_ZRB_DEPLOYMENT_NAME}/index.yaml'
    _registerAppRunnerTasks: ''
    _registerAppDeploymentTasks: ''
    _validateAppDirectory: ''
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/eksDeployment/deploymentTaskTemplate"
      ]