from modules.ztplAppModuleName.route import register_ztpl_app_module_name_api_route, register_ztpl_app_module_name_ui_route
from modules.ztplAppModuleName.event import register_ztpl_app_module_name_event_handler
from modules.ztplAppModuleName.rpc import register_ztpl_app_module_name_rpc_handler