configs:

  update:
    start: |
      cd "{{ .ZarubaHome }}"
      echo "🔽 ${_BOLD}${_YELLOW}Pull zaruba${_NORMAL}"
      git checkout master
      git pull origin master
      git fetch --tag
      echo "${_CONSTRUCTION_ICON} ${_BOLD}${_YELLOW}Compile zaruba${_NORMAL}"
      . ./buildZaruba.sh
      echo ${_SUCCESS_ICON}${_SUCCESS_ICON}${_SUCCESS_ICON}
      echo "${_BOLD}${_YELLOW}Zaruba ready!!!${_NORMAL}"
      echo "${_BOLD}${_YELLOW}$("{{ .ZarubaBin }}" version)${_NORMAL}"