configs:

  ztplAppName:
    runInLocal: '{{ .GetValue "runZtplAppNameInLocal" }}'
    ports: |
      ztplAppYamlPorts

  ztplAppNameContainer:
    useImagePrefix: true
    imageName: ztpl-app-image-name
    containerName: ztplAppContainerName
    localhost: host.docker.internal
    memory: 2g
    afterCheck: sleep 5
    checkCommand: |
      ztplAppCheckCommand
    command : |
      ztplAppStartContainerCommand
    volumes: |
      ztplAppYamlContainerVolumes