configs:

  ztplAppName:
    runInLocal: '{{ .GetValue "runZtplAppNameInLocal" }}'
    ports: |
      ztplAppYamlPorts
    afterCheck: sleep 5
    checkCommand: |
      ztplAppCheckCommand

  ztplAppNameImage:
    useImagePrefix: true
    imageName: ztpl-app-image-name