configs:

  makeNginxAppRunner:
    appIcon: 📗
    defaultAppDirectory: '{{ .ProjectName }}Nginx'
    defaultAppPorts: |
      [
        "80",
        "443"
      ]
    defaultAppContainerVolumes: |
      [
        "letsencrypt:/etc/letsencrypt",
        "html:/opt/bitnami/nginx/html",
        "server_blocks:/opt/bitnami/nginx/conf/server_blocks"
      ]
