configs:

  makeCassandraAppRunner:
    appIcon: 👀
    appCheckCommand: cqlsh -u "{{ .Template ".GetEnv \"CASSANDRA_USER\"" }}" -p "{{ .Template ".GetEnv \"CASSANDRA_PASSWORD\"" }}" -e "describe cluster"
    defaultAppDirectory: '{{ .ProjectName }}Cassandra'
    defaultAppPorts: |
      [
        "{{ .Template ".GetEnv \\\"CASSANDRA_TRANSPORT_PORT_NUMBER\\\"" }}",
        "{{ .Template ".GetEnv \\\"CASSANDRA_JMX_PORT_NUMBER\\\"" }}",
        "{{ .Template ".GetEnv \\\"CASSANDRA_CQL_PORT_NUMBER\\\"" }}"
      ]
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/_base/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/appRunner/dockerContainer/template",
        "{{ .ZarubaHome }}/zaruba-tasks/make/cassandra/appRunnerTemplate"
      ] 