_PROJECT_FILE_NAME="${1}"
_MODULE_FILE_NAME="${2}"
_APP_NAME="${3}"
"${ZARUBA_HOME}/zaruba" project include "${_PROJECT_FILE_NAME}" "${_MODULE_FILE_NAME}"
"${ZARUBA_HOME}/zaruba" project syncEnvFiles "${_PROJECT_FILE_NAME}"