_setReplacementMap "zrbAppBuildImageCommand" "${_ZRB_APP_BUILD_IMAGE_COMMAND}"
_setReplacementMap "zrbAppContainerName" "${_ZRB_APP_CONTAINER_NAME}"
_setReplacementMap "zrbAppDependencies" "${_ZRB_APP_DEPENDENCIES}"
_setReplacementMap "zrbAppDirectory" "${_ZRB_APP_DIRECTORY}"
_setReplacementMap "zrbAppEnvPrefix" "${_ZRB_APP_ENV_PREFIX}"
_setReplacementMap "zrbAppEnvs" "${_ZRB_APP_ENVS}"
_setReplacementMap "zrbAppHelmChartUrl" "${_ZRB_APP_HELM_CHART_URL}"
_setReplacementMap "zrbAppImageName" "${_ZRB_APP_IMAGE_NAME}"
_setReplacementMap "zrbAppName" "${_ZRB_APP_NAME}"
_setReplacementMap "zrbAppPorts" "${_ZRB_APP_PORTS}"
_setReplacementMap "zrbAppPushImageCommand" "${_ZRB_APP_PUSH_IMAGE_COMMAND}"
_setReplacementMap "zrbAppRunnerVersion" "${_ZRB_APP_RUNNER_VERSION}"
_setReplacementMap "zrbAppStartCommand" "${_ZRB_APP_START_COMMAND}"
_setReplacementMap "zrbAppStartContainerCommand" "${_ZRB_APP_START_CONTAINER_COMMAND}"
_setReplacementMap "zrbAppTestCommand" "${_ZRB_APP_TEST_COMMAND}"
_setReplacementMap "[\t ]*zrbAppYamlPorts" "${_ZRB_APP_YAML_PORTS}"
_setReplacementMap "[\t ]*zrbAppYamlEnvs" "${_ZRB_APP_YAML_ENVS}"

echo "${_ZRB_REPLACEMENT_MAP}"