configs:

  ztplDeploymentName:
    pulumiStack: '{{ if .GetValue "pulumiStack" }}{{ .GetValue "pulumiStack" }}{{ else }}dev{{ end }}'
    awsRegion: '{{ if .GetValue "ztplDeploymentNameRegion" }}{{ .GetValue "ztplDeploymentNameRegion" }}{{ else }}us-east-2{{ end }}'
    pulumiSelectStack: |
      PULUMI_STACK='{{ .GetConfig "pulumiStack" }}'
      AWS_REGION='{{ .GetConfig "awsRegion" }}'
      pulumi stack select "${PULUMI_STACK}" || pulumi stack init "${PULUMI_STACK}"
      pulumi config set aws:region "${AWS_REGION}"

  deployZtplDeploymentName:
    start: |
      {{ .GetConfig "pulumiSelectStack" }}
      pulumi up -y

  destroyZtplDeploymentName: 
    start: |
      {{ .GetConfig "pulumiSelectStack" }}
      pulumi destroy -y

  prepareZtplDeploymentName:
    start: |
      if [ ! -d "./venv" ]
      then
        python -m venv ./venv
      fi
      source ./venv/bin/activate
      pip install -r requirements.txt
      if [ ! -f "${PUBLIC_KEY_PATH}" ] || [ ! -f "${PRIVATE_KEY_PATH}" ]
      then
        ssh-keygen -b 2048 -t rsa -f "${PUBLIC_KEY_PATH}" -q -N ""
      fi