configs:
 
  makeEc2Deployment:
    appIcon: 📙
    defaultDeploymentDirectory: '{{ .ProjectName }}Ec2'
    ec2Region: '{{ .GetValue "ec2Region" }}'
    ec2ClusterName: '{{ if .GetValue "ec2ClusterName" }}{{ .GetValue "ec2ClusterName" }}{{ else }}{{ .ProjectName }}{{ end }}'
    _skipCreationPath: '${_ZRB_DEPLOYMENT_DIRECTORY}'
    _prepareVariables: |
      _ZRB_EKS_REGION='{{ .GetConfig "ec2Region" }}'
      _ZRB_EKS_CLUSTER_NAME={{ .Util.Str.ToKebab (.GetConfig "ec2ClusterName") }}
    _prepareReplacementMap: |
      _setReplacementMap "ztpl-region" "${_ZRB_EKS_REGION}"
      _setReplacementMap "ztpl-cluster-name" "${_ZRB_EKS_CLUSTER_NAME}"ec2Region: '{{ if .GetValue "ec2Region" }}{{ .GetValue "ec2Region" }}{{ else }}us-east-1{{ end }}'
    _validateAppDirectory: ''
    templateLocations: |
      [
        "{{ .ZarubaHome }}/zaruba-tasks/make/ec2Deployment/deploymentTemplate"
      ]