from module.ztpl_app_module_name.route import register_ztpl_app_module_name_api_route, register_ztpl_app_module_name_ui_route
from module.ztpl_app_module_name.event import register_ztpl_app_module_name_event_handler
from module.ztpl_app_module_name.rpc import register_ztpl_app_module_name_rpc_handler